### ISSUE TITLE
Add timer to all actions

### ISSUE THREAD

**Issue by dusktreader** [zudijyr/Building-Sim-Game#17]
This will allow us to tell if it is the first time that an action has been executed.

This will be useful, for example, in constructing buildings. If the time is 0.0, we can drop a scaffold where the building will be, and then replace the scaffold with the complete building when the building is done being constructed.

**Comment by zudijyr** [comment]
Doesn't the "elapsed_time" attribute handle this?

**Comment by dusktreader** [comment]
That was recently added. This issue can be closed
