### ISSUE TITLE
Figure out why game crashes if you right click on a unit (exactly)

### ISSUE THREAD

**Issue by dusktreader** [zudijyr/Building-Sim-Game#18]
If you right click exactly on the center of a unit when it is selected (to move it to the place you click), the game crashes:

  File "/home/dusktreader/work/Building-Sim-Game/sim/models/tile_map.py", line 87, in move_unit
    raise TileMapException("Unit may not move out of bounds")
sim.models.tile_map.TileMapException: Unit may not move out of bounds

This must be some sort of divide by zero error or something.

**Comment by zudijyr** [comment]
I was able to fix this by adding an error check in the move action.  Not sure *exactly* why this was happening but yeah some sort of divide by zero error.

**Comment by dusktreader** [comment]
good enough for me!
