### ISSUE TITLE
add option to harvest action to gather until unit is at capacity

### ISSUE THREAD

**Issue by dusktreader** [zudijyr/Building-Sim-Game#19]
'nuff said.

Maybe this should be the default behavior?

**Comment by zudijyr** [comment]
Yeah that should be the default.  I don't know if we even need an option to *not* gather until capacity... seems like you'd very rarely want to do that, and you can do it by manually pulling them off if you want.

**Comment by zudijyr** [comment]
I'm not really sure how to implement this though.  Now that actions are their own separate class, the harvest action has no way of knowing what the unit's capacity is.

**Comment by dusktreader** [comment]
the unit is passed to the action's methods, so it can just check the units capacity in the is_complete method

**Comment by zudijyr** [comment]
I fixed this by changing the initial quantity to the unit's remaining capacity.  I think you'll almost always want to harvest all the way, so it might as well be the default behavior.
