### ISSUE TITLE
Limit movement on tiles to certain units

### ISSUE THREAD

**Issue by dusktreader** [zudijyr/Building-Sim-Game#21]
Not all tiles should be navigable by all units. Ships should be confined to water tiles, and peasants shouldn't be able to move over water

**Comment by zudijyr** [comment]
I have a commit based on your interactivity branch that handles this.    It doesn't raise an error, it just makes them stop, so you can order a ship towards land and it'll get as close as possible then stop.

**Comment by zudijyr** [comment]
We also need to block units from moving onto space occupied by another unit or a building

**Comment by dusktreader** [comment]
yeah, just having them stop is the right thing to do.

Blocking by buildings or other units is a good thing to do, as well. Maybe open a new issue for that?
