### ISSUE TITLE
Fix GUI blocked zooming

### ISSUE THREAD

**Issue by zudijyr** [zudijyr/Building-Sim-Game#36]
the pyglet-gui that we just added seems to have messed up the zoom feature.  Panning still works though.

**Comment by dusktreader** [comment]
Like I suspected this was an issue with the pyglet-gui library. I've patched it an pushed the change up to my fork of the repo. So, if you reinstall the pyglet-gui library, it should work correctly.

Also, our friend that owns the pyglet-gui library hasn't been online still (getting impatient)
